### ISSUE TITLE
Recources missing

### ISSUE THREAD

**Issue by PetkoAndreev** [SoftUni-Internal/hackathon-issues#10]
I have download resources only on the first task. For the remaining 4 the link/button is missing.
![image](https://user-images.githubusercontent.com/77919922/207855175-253fc930-8f15-4a00-8e5d-d9fdea6506de.png)

**Comment by Innos** [comment]
Problem descriptions were meant to all be in the same file attached to the 1st problem

**Comment by PetkoAndreev** [comment]
As a suggestion it'll be good to have some user orientation that the resources are for all tasks in case of open directly the second or above ones.
