### ISSUE TITLE
Missing Navigation or programming language and/or course in the name of the contest

### ISSUE THREAD

**Issue by PetkoAndreev** [SoftUni-Internal/hackathon-issues#102]
When I open a contest (example - https://judgesoftuniorg.ml/contests/1718/practice#1) it's hard to see for which language and course level is. You can check only by the submission language, but there is no like in old judge a navigation bar to show the course name and the programming language.
![image](https://user-images.githubusercontent.com/77919922/207877895-ff04cde2-df29-41c0-99e9-bda28f721287.png)

**Comment by MadjarovaML** [comment]
@innos please consider it for our upcoming meeting.
We'll need an issue with more details in order to implement it
