### ISSUE TITLE
Removing "disabled" property from "Practice" button does not lead to error page.

### ISSUE THREAD

**Issue by kalin729** [SoftUni-Internal/hackathon-issues#103]
**Describe the bug**
When removing the "disabled" property from a "Practice" button from contest, it does not redirect you to an error page, but to a page, saying "No password required. Redirecting to contest.".

**Steps To Reproduce**
1. Open Contests
2. Find a contest that does not let you click "practice".
3. Remove "disabled" from the button
4. Click the button

**Screenshots**
![image](https://user-images.githubusercontent.com/24556064/207878967-aae21deb-3ca5-46f4-a0c5-f39d920becf3.png)
![image](https://user-images.githubusercontent.com/24556064/207879189-8b421535-f942-46c9-a622-ad2c21147e84.png)
![image](https://user-images.githubusercontent.com/24556064/207879322-86e3bd17-672c-4298-a1fa-bc189afc9c93.png)
![image](https://user-images.githubusercontent.com/24556064/207879412-793ab2ce-9847-4c57-83a3-b5f9b8c3f836.png)
![image](https://user-images.githubusercontent.com/24556064/207879570-267dfe39-c28d-4a85-9fd0-9af894b9bd13.png)

**Additional context**

**Comment by Innos** [comment]
Need to test whether there are server level protections entering a contest/practice that is not in it's active duration, using a test user

**Comment by MadjarovaML** [comment]
@Innos  log a particular response if you want us to add some changes.
if the course is set up properly in the administration it will always has some of the buttons enabled if it doesn't the contest must be hidden
