### ISSUE TITLE
Time gap

### ISSUE THREAD

**Issue by VankoIvanov** [SoftUni-Internal/hackathon-issues#104]
**Describe the bug**
With an open race it shows one thing and with the race page it shows another time

**Steps To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/74661739/207879085-f51d6401-75e8-4128-a9d5-7cb984f65259.png)
![image](https://user-images.githubusercontent.com/74661739/207879347-4ff1bdad-033d-45ab-832e-4aa06ae9b626.png)

**Additional context**

**Comment by Innos** [comment]
The answer is the same as in this issue https://github.com/SoftUni-Internal/hackathon-issues/issues/122
