### ISSUE TITLE
Trying to download resources from joined contest for practice wants a password for http://svn.softuni.org/

### ISSUE THREAD

**Issue by kalin729** [SoftUni-Internal/hackathon-issues#106]
**Describe the bug**
When trying to download resources from a contest that I joined via the "Practice" button, it sent me to "http://svn.softuni.org/admin/svn/(contest link)" wanting a username and password from me.
**Steps To Reproduce**
1. Join contest
2. Try to download Resources

**Screenshots**
![image](https://user-images.githubusercontent.com/24556064/207882039-96616ef4-8694-4886-83de-6a0aa0878225.png)

**Additional context**

**Comment by MadjarovaML** [comment]
in order to check and reproduce it I need the contest ID @Innos
