### ISSUE TITLE
Problem with the timer

### ISSUE THREAD

**Issue by AntoanPetrov123** [SoftUni-Internal/hackathon-issues#107]
**Describe the bug**
Somehow it was showing ~  1:35:00 after refresh it was set back to ~ 1:21:00 
This happent when I was not in the contest and doing somthig else
**Steps To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/72857425/207881760-b94e33a8-bc01-432a-8729-57d50af44f50.png)

**Additional context**

**Comment by AntoanPetrov123** [comment]
I could't screenshot the timer with the wrong digits

**Comment by Innos** [comment]
If the tab was inactive, the browser probably pulled resources from the tab, leading to the timer not changing and resuming only when the tab was active again. Need to add a interval task or alarms that will synchronize the timer with the actual time.
