### ISSUE TITLE
Click on contest name in the Submission page is not working

### ISSUE THREAD

**Issue by dtdimitrovv** [SoftUni-Internal/hackathon-issues#108]
**Describe the bug**
When we try to load the contest a submission belongs to we can get an empty page

**Steps To Reproduce**
1 - Go to Submissions page
2 - Click on the name of a recent one
3 - Observe

**Screenshots**
![image](https://user-images.githubusercontent.com/86721304/207884899-59dc1211-f8e7-4c49-b64a-5a0c200f425d.png)

**Additional context**

**Comment by Innos** [comment]
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/41
