### ISSUE TITLE
Contest buttons disabled

### ISSUE THREAD

**Issue by PetkoAndreev** [SoftUni-Internal/hackathon-issues#109]
When filter some contests - example Programming Basics with Python for one of the contest there is a timer and the link buttons Compete and Practice are disabled.
![image](https://user-images.githubusercontent.com/77919922/207885182-38019c32-4e1f-4587-ab9b-596fb1da483a.png)

**Comment by MadjarovaML** [comment]
It is due to administration set up. 
The contest is marked as visible bur neither of compete or contest time is set.
