### ISSUE TITLE
Contest - click Practice not open the contest

### ISSUE THREAD

**Issue by PetkoAndreev** [SoftUni-Internal/hackathon-issues#111]
When click on Practice of the contest for Python Web Exams it open blank page with url (https://judgesoftuniorg.ml/contests/undefined/undefined#1):
![image](https://user-images.githubusercontent.com/77919922/207885798-b318c549-785d-4069-909a-5dbebb95f6f7.png)

**Comment by Innos** [comment]
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/27

Connected issue https://github.com/SoftUni-Internal/hackathon-issues/issues/113
