### ISSUE TITLE
Contest - back functionality

### ISSUE THREAD

**Issue by PetkoAndreev** [SoftUni-Internal/hackathon-issues#113]
After trying to open contest (Python Web Basics Exams) and it navigates to invalid url (https://judgesoftuniorg.ml/contests/undefined/undefined#1). When on this page - https://judgesoftuniorg.ml/contests/undefined/undefined#1 and click two times back arrow in the browser it opens one of the example exams - https://judgesoftuniorg.ml/contests/2602/practice#1
![image](https://user-images.githubusercontent.com/77919922/207886992-4b9b2c95-eeca-4cfb-9c93-161cb4670bfa.png)

**Comment by Innos** [comment]
This issue gives some context about the bug that sometimes happens when you get undefined instead of the contest, as it appears the actual contest page was pushed to the browser history, but 2 extra history states get pushed on top of it
