### ISSUE TITLE
Contest Score - null

### ISSUE THREAD

**Issue by PetkoAndreev** [SoftUni-Internal/hackathon-issues#114]
When open a contest - https://judgesoftuniorg.ml/contests/2602/practice#1 in the score there are null/100 instead of 0/100:
![image](https://user-images.githubusercontent.com/77919922/207887164-946e3382-aaac-4a07-b581-4853d825272f.png)

**Comment by Innos** [comment]
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/88
