### ISSUE TITLE
Contests - resources language

### ISSUE THREAD

**Issue by PetkoAndreev** [SoftUni-Internal/hackathon-issues#116]
For some contests the language for the resources is in English and for some is in Bulgarian:
English:
![image](https://user-images.githubusercontent.com/77919922/207887958-66c10827-c1cb-4763-8196-7c887bf35d82.png)
Bulgarian:
![image](https://user-images.githubusercontent.com/77919922/207888046-6adcc502-ba52-4f48-aba8-33fa574b3392.png)

**Comment by Innos** [comment]
It just depends on what name, whoever set up the resources wrote, but it works as intended and is not a problem with the system.

**Comment by PetkoAndreev** [comment]
It can be set a check if the language is not English to provide the message to the user to enter the text in English. Just as proposition as a good practice is all to be in one language.
