### ISSUE TITLE
My Profile column settings may not be aligned one under another

### ISSUE THREAD

**Issue by kalin729** [SoftUni-Internal/hackathon-issues#118]
**Describe the bug**
In a few occasions the column settings in "My Profile" bugged their alignment.

**Steps To Reproduce**
1. Open "My Profile" page
2. Open "Contest Participations"
3. Click on the 3 dots on a column

**Screenshots**
The way they bugged: 
![image](https://user-images.githubusercontent.com/24556064/207889196-533113d1-549d-4f5b-8eb9-8308c8bdc507.png)
The way they should be: 
![image](https://user-images.githubusercontent.com/24556064/207889404-d4610a9d-91e4-4088-a30d-762b9d1ba6ae.png)

**Comment by MadjarovaML** [comment]
it is a responsive issue which is already logged
