### ISSUE TITLE
Contest - points UI colors

### ISSUE THREAD

**Issue by PetkoAndreev** [SoftUni-Internal/hackathon-issues#119]
When starting a contest and the points are ?/100 - the color combination of light orange and white for the numbers it's a little not good visible/ As a proposition if the numbers are bold will be better.
![image](https://user-images.githubusercontent.com/77919922/207889526-6d68500c-5f4d-46b7-9487-4efaae806cd6.png)

**Comment by MadjarovaML** [comment]
@Innos it is by initial design if you want to add those changes to our repo, please log an issue with a suggestion.
?/100 is excepted behavior when there is no submit. We can set all of them 0/100
