### ISSUE TITLE
My Profile - Contests Sorting

### ISSUE THREAD

**Issue by PetkoAndreev** [SoftUni-Internal/hackathon-issues#120]
Sorting on Time column works, but it's confusing, because of the date. As a regular student/user I'll expect to sort not only by time values, but by date also since it's included and visible. Here is an example:
![image](https://user-images.githubusercontent.com/77919922/207890374-b5fdf55f-fc5b-499f-86cf-210ad76904e0.png)

**Comment by Innos** [comment]
Sorting seems inconsistent, desc/asc each generate at least 3 different sort orders and cycle through them
