### ISSUE TITLE
Hackaton contest timer not correct

### ISSUE THREAD

**Issue by PetkoAndreev** [SoftUni-Internal/hackathon-issues#122]
The timer for today's Hackaton contest is not correctly setup. The contest is from 14:00 to  17:00 and in the contest is visible one more hour:
![image](https://user-images.githubusercontent.com/77919922/207892180-54eac7a4-7bc6-4be0-9ba1-cd839da09afe.png)

**Comment by Innos** [comment]
There is a contest overall time during which the users can start the contest and there is personal time, i.e. the time you have after you start the contest.

**Comment by PetkoAndreev** [comment]
Yes I know the difference in the times and I started the contest around 14:01 + 3 hrs is 17:01. Anyway after refresh around 17:10 it were no more available.

**Comment by Innos** [comment]
if you were locked out after 17:00 sounds like it works correctly
