### ISSUE TITLE
Submission timer bugs when window is inactive.

### ISSUE THREAD

**Issue by kalin729** [SoftUni-Internal/hackathon-issues#124]
**Describe the bug**
When submitting a result and leaving the contest window inactive, the submission timer bugs out.
Tested with a stopwatch on my phone.
Started stopwatch at 1:15 left.
Checked window at 1:23 elapsed.
Provided screenshot of the stopwatch at 1:23 and the submission timer after 1:23min

**Steps To Reproduce**
1. Submit result
2. Start stopwatch
3. Leave window
4. Check back later

**Screenshots**
![image](https://user-images.githubusercontent.com/24556064/207892675-06d5164a-2dd1-41ae-bbc4-d2911948005d.png)
![image](https://user-images.githubusercontent.com/24556064/207892695-35f6d685-3b4c-47ff-85df-78ccb1f11359.png)

**Comment by Innos** [comment]
Probably similar to https://github.com/SoftUni-Internal/hackathon-issues/issues/107, but for the time until next submit timer, however not sure if we need to support synchronization for such small time frames

**Comment by kalin729** [comment]
I find it important for myself, that the submission timer to be correct. Many students go back to their IDE to continue their tasks in while they wait for the submission timer to end and it can confuse them.
