### ISSUE TITLE
Changing link from "practice" to "compete" returns blank contest.

### ISSUE THREAD

**Issue by kalin729** [SoftUni-Internal/hackathon-issues#129]
**Describe the bug**
Opening a contest through "Practice" and changing its link to "compete" returns a blank contest, instead of appropriate error message or just redirect to "practice" again. Also works the same way around.
Changed: https://judgesoftuniorg.ml/contests/3308/practice#1
To: https://judgesoftuniorg.ml/contests/3308/compete#1

**Steps To Reproduce**
1. Open contest
2. Replace "compete" or "practice" with the opposite

**Screenshots**
Before: 
![image](https://user-images.githubusercontent.com/24556064/207925134-05e8c1a3-3204-483c-9a41-9e6b9a14a903.png)
After: 
![image](https://user-images.githubusercontent.com/24556064/207925196-d72307e4-7fc6-452e-9fce-45b77255bca4.png)

**Comment by Innos** [comment]
Sounds like a more specific case of https://github.com/SoftUni-Internal/hackathon-issues/issues/137, but I'll leave both as enhancement ideas
