### ISSUE TITLE
Adding "/logout" while logged out gets stuck in a page that says "You will be redirected".

### ISSUE THREAD

**Issue by kalin729** [SoftUni-Internal/hackathon-issues#131]
**Describe the bug**
Logging out of your profile and adding "/logout" to the link opens a page that says "You are logged out. You will be redirected to home shortly." and stays in that page.

**Steps To Reproduce**
1. Logout 
2. Add "/logout" to the address

**Screenshots**
![image](https://user-images.githubusercontent.com/24556064/207929390-0b5318cc-8664-45cf-a1e1-bce52d96ded8.png)

**Comment by Innos** [comment]
It doesn't sound too wrong to me, probably adding an auto redirect to home, after calling /logout  is going to be better though, not that you should see any button for Logout after you've already logged out

**Comment by kalin729** [comment]
I also think redirecting to home would fix it.
