### ISSUE TITLE
Contests - Strategy issue and proposition

### ISSUE THREAD

**Issue by PetkoAndreev** [SoftUni-Internal/hackathon-issues#133]
The issue part is when click on some value after expanding:
![image](https://user-images.githubusercontent.com/77919922/207933667-51f40ae1-d336-4423-b290-e9713c2cd229.png)
After hide the values there is a possibility to forgot what you filter and the choosed value is not visible:
![image](https://user-images.githubusercontent.com/77919922/207933842-f14eee1b-9a34-4810-8f14-4b9f100f3c86.png)
In addition it's not possible to choose more than one value - for example if I want to show contests for Python Fundamentals and Python OOP it will be no possible to choose from Python Project Unittests and Python code.

It'll be good to think to implement it differently, because when click show more the list is bigger and you need to scroll a lot to check all values. Here are 2 example propositions:
1. To be splitted horizontally under the contests and when expand all values will be visible in 2-3 rows.
2. To be with dropdown choice menu + logic when typing for example "Pyt" to show all the values which starts or contains "Pyt" - search like logic.

**Comment by Innos** [comment]
Similar to https://github.com/SoftUni-Internal/hackathon-issues/issues/89, however we can consider this an enhancement idea, to use a multi select with auto complete
