### ISSUE TITLE
Contest - invalid number in url

### ISSUE THREAD

**Issue by PetkoAndreev** [SoftUni-Internal/hackathon-issues#137]
When enter invalid contest number in the url it shows undefined (https://judgesoftuniorg.ml/contests/30100/practice#1). My suggestion is that the expected behavior should be to open 404 or something like There is no such contest, please go to Contests page and check from the available ones.
![image](https://user-images.githubusercontent.com/77919922/207950358-c9ef989f-e422-4512-9504-9c91d47584fd.png)

**Comment by Innos** [comment]
Similar to https://github.com/SoftUni-Internal/hackathon-issues/issues/132 and https://github.com/SoftUni-Internal/hackathon-issues/issues/125, but probably should consider it as an idea, to have separate logic for trying to join a contest that has ended
