### ISSUE TITLE
Contests - Exam more than one language to choose

### ISSUE THREAD

**Issue by PetkoAndreev** [SoftUni-Internal/hackathon-issues#138]
Some exam contests are with two possibilities for language which probably is not fine. Example is this contest for Java Sample Exam where language options are C# and Java. I think that it should be only Java in that case.
![image](https://user-images.githubusercontent.com/77919922/207951377-3b438514-9757-48ec-87fa-2c7a3e2c048d.png)

**Comment by Innos** [comment]
Sounds like an administrative issue, not a problem with the system
