### ISSUE TITLE
Switching between different problems freezes time counting

### ISSUE THREAD

**Issue by Moonriderx** [SoftUni-Internal/hackathon-issues#14]
**Describe the bug**
Spamming different problems freezes the time count

**Steps To Reproduce**

Switch between different problems

**Video**

https://user-images.githubusercontent.com/65513534/207856553-0bef731e-be64-444c-988c-8e5253571441.mp4

**Additional context**
It fixes on refresh but may cause long-term changes to time and timer

**Comment by MadjarovaML** [comment]
As far as I can see in your video the timer continues to count down the time during the switching.
Please contact me in order to discuss it if I'm wrong
