### ISSUE TITLE
The button doesn't work

### ISSUE THREAD

**Issue by VankoIvanov** [SoftUni-Internal/hackathon-issues#148]
**Describe the bug**
The button doesn't work

**Steps To Reproduce**
When opening the details of the tests. 

**Screenshots**
![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/74661739/6a8c3879-34bb-4cce-a690-6693d3f2f42f)

**Additional context**

**Comment by veronika793** [comment]
@VankoIvanov  please add more details with links so we know where it's located.

**Comment by Innos** [comment]
![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/12100545/cb49e67c-88e0-44a5-9cae-ada7b1799120)
Assuming its based on the fact, that having one submission in the submission list in Submission details, shows the selected submission with a greyed out Details button. While this is consistent in color scheme with how we show the selected strategy for example, I would agree that with grey as the color of choice, we should probably add more expressive ways to show that this is the currently selected submission, like coloring the entire current item with some color to differentiate it from the others.

This entire rectangle should be colored/highlighted to show it is the selected item and if in a list like this example, the scroller should be auto scrolled to it as well.
![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/12100545/a653fc16-2c2a-4b67-ae13-c62fc750b8b4)

**Comment by VankoIvanov** [comment]
It's just not clear if this button is active or not. Is it currently clicked? Because in one result it is clearly clicked, but it gives the feeling that you have to click on it for more details. Also you mentioned it has to scroll. As a solution, it can also be hidden when a solution is selected. So when you click on the details of another solution, you can see them. And it becomes more intuitive that you are at the moment of the current details
