### ISSUE TITLE
No result for an explosive decision

### ISSUE THREAD

**Issue by VankoIvanov** [SoftUni-Internal/hackathon-issues#149]
**Describe the bug**
Judge does not indicate if the test failed and for what reason. You have to open the details to see that the test failed

**Steps To Reproduce**
when a decision is passed on the right side, there is no information about the test that it has failed. When you open the details then you see. 
Looks like it's still being processed.

**Screenshots**

![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/74661739/0399729d-7bba-48d6-b35b-b105caef3479)
![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/74661739/bb1e9fe5-7cbf-4dda-8e85-2f027500e9b2)

**Additional context**
Link to submission: https://alpha.judge.softuni.org/submissions/2962/details

**Comment by veronika793** [comment]
related https://github.com/SoftUni-Internal/hackathon-issues/issues/147

**Comment by Innos** [comment]
The class name in the submit is in cyrillic and while Java itself may support unicode class names, the terminal where the code (and thus the class name is called) don't necessarily need to support them. Anyway code conventions and good practices frown upon using non-english, class names and the compile time errors states that a valid class name was not found, which is the expected result in this case. Also the behavior is consistent with the current judge.
