### ISSUE TITLE
GitHub icon and YouTube icons in footer

### ISSUE THREAD

**Issue by StanimirResh** [SoftUni-Internal/hackathon-issues#151]
**Describe the bug**
Icons in the footer don't work properly.

**Steps To Reproduce**
When clicked they lead to
https://alpha.judge.softuni.org/https://www.youtube.com/channel/UCqvOk8tYzfRS-eDy4vs3UyA
or
https://alpha.judge.softuni.org/https://github.com/NikolayIT/OpenJudgeSystem
instead of just https://github.com/NikolayIT/OpenJudgeSystem

**Screenshots**
![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/80858802/4c07b2ff-eb0b-4086-bffa-db33a9e35068)

**Additional context**

**Comment by KaiserDMC** [comment]
In addition there is lack of any margins or padding at least on my side for those same icons. They look like they are trying to collapse on each other:
![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/63681999/2fa19727-b554-4592-83b7-6cce0cc8e817)
