### ISSUE TITLE
Two of the buttons do not work on a translated page

### ISSUE THREAD

**Issue by VankoIvanov** [SoftUni-Internal/hackathon-issues#152]
**Describe the bug**

**Steps To Reproduce**
When you translate the page into another language, the two buttons my solutions and all solutions become inactive

In the submissions page - https://alpha.judge.softuni.org/submissions?toggle=my&page=1
**Screenshots**

![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/74661739/3ad09d0f-8d06-4a24-8cfd-8a1f5da195c3)

**Additional context**

**Comment by Innos** [comment]
The original site does not have these problems and at this point expecting support for specific functionality of the google translate transformed version of the site, seems out of scope for this, so I'm closing this issue as invalid.
