### ISSUE TITLE
The four paths are missing

### ISSUE THREAD

**Issue by VankoIvanov** [SoftUni-Internal/hackathon-issues#154]
**Describe the bug**
The four paths are missing

**Steps To Reproduce**

In the catalog page of the catalog menu, all program paths are missing

https://learn.softuni.org/catalog

**Screenshots**
![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/74661739/1446ff3d-322e-4a7c-acdb-af1d25d0e501)

**Additional context**

**Comment by Innos** [comment]
This issue is not relevant to judge.
