### ISSUE TITLE
 The field for email at the login

### ISSUE THREAD

**Issue by VankoIvanov** [SoftUni-Internal/hackathon-issues#155]
**Describe the bug**
It says that you log in with an email, but you can also use a username, but the validity is for an email

**Steps To Reproduce**
When logging in

**Screenshots**
![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/74661739/045a2b7d-ec32-4f45-8d6b-7cbd9a261f83)

**Additional context**

**Comment by Innos** [comment]
This issue is not relevant to judge.
