### ISSUE TITLE
Submissions - not all visible

### ISSUE THREAD

**Issue by PetkoAndreev** [SoftUni-Internal/hackathon-issues#161]
If it's not a desired effect - it'll be good to see the other submission like in the current judge.

![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/77919922/619b12a9-e534-4bda-a9aa-e5487650174f)

**Comment by Innos** [comment]
I'm assuming talking about the fact that you can see only a limited amount of your submission (4) for a particular problem and if you submit more than 4 times, you can no longer see you older submits within the contest or even in the submission details for the problem.
