### ISSUE TITLE
Strategy bug 2

### ISSUE THREAD

**Issue by PetkoAndreev** [SoftUni-Internal/hackathon-issues#166]
When filter by Strategy and try to choose Select strategy and then to pick another one it cannot be done and the possible values are only choosed strategy and "Select strategy":

![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/77919922/6d6862eb-826e-49bd-80fb-a63956491522)

**Comment by Innos** [comment]
The list of available strategies in the dropdown depends on which category is currently selected and the list of strategies is filtered to only show the strategies that are available in this category.

Given that there is no other strategy in the dropdown list and Select strategy is just an unselectable placeholder (as intended), this appears to be working as expected, if there was a second strategy in the dropdown, you could freely change them.
