### ISSUE TITLE
Register to Login

### ISSUE THREAD

**Issue by PetkoAndreev** [SoftUni-Internal/hackathon-issues#168]
When transferred to the register page and try to click on login it just transfer to the other page and not to the login one:

![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/77919922/473b8edb-2911-4dfe-8bc5-dda8abf0f36b)

After the button is clicked:

![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/77919922/39ff8aaf-a1f3-4bca-b699-c77ede49d5a1)

**Comment by KaiserDMC** [comment]
Same issue found with the other redirect button on the same form:
![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/63681999/53aab7e6-a764-4707-8a96-6ba2f8b8ee29)
