### ISSUE TITLE
Contest results ordering by task points and Full Name not possible

### ISSUE THREAD

**Issue by PetkoAndreev** [SoftUni-Internal/hackathon-issues#176]
When try to order the contest results by points it's not possible. Also button for ordering is missing on the Full Name column:

![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/77919922/3b00a7d2-d297-4042-9773-b843e965be63)

![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/77919922/0eb402dd-9a25-4b08-b333-4d0ce9335640)

*Note - ordering by Position and applying a filter to a Full Name works.

**Comment by veronika793** [comment]
related https://github.com/SoftUni-Internal/hackathon-issues/issues/167

**Comment by Innos** [comment]
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/167
