### ISSUE TITLE
Refresh Button - Submissions

### ISSUE THREAD

**Issue by KaiserDMC** [SoftUni-Internal/hackathon-issues#178]
**Describe the bug**
The refresh button changes position based on the amount of submission for the current task.

**Steps To Reproduce**
Submit a single solution to a task and check the location of Refresh button. Proceed to submit more and more to see how the position of the button is changed.

**Screenshots**
Location with one submit
![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/63681999/03ca567b-f86b-449b-9639-9a4d32c84f6b)

Location with multiple submits
![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/63681999/e2ce22ef-a648-40b7-aed8-4687890f9693)

**Additional context**
Current implementation has the refresh button in the same exact spot, making it easier for muscle memory. The new implementation changes the button location further down the body of the container with each submission making it very hard to find and click.
Suggested option for new location could be on the same level as the "Submissions" header:
![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/63681999/74424962-7257-4e14-a504-451885679441)
As this is more or less the default location without any submissions:
![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/63681999/e23f2dd1-07be-4af8-a537-1c65c75a8ed5)

**Comment by Innos** [comment]
Closing this recommendation, as the way submissions will be loaded is going to change and is expected to not need a refresh button.
