### ISSUE TITLE
Footer link not properly navigating

### ISSUE THREAD

**Issue by PetkoAndreev** [SoftUni-Internal/hackathon-issues#179]
Two of the footer links are leading to a different pages, not the one mentioned:
Blog - leads to https://softuni.org/, not to the blog itself. Logo navigates to the judge and not to the SoftUni website as expected.
![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/77919922/4d9e70cd-1eed-4caf-9c89-ac4e6f9edfd9)
![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/77919922/c59b8144-bf23-4faf-9623-06dc2fd325e0)

**Comment by veronika793** [comment]
related https://github.com/SoftUni-Internal/hackathon-issues/issues/151

**Comment by Innos** [comment]
I'm removing the recommendation and leaving this as a normal issue, since the Home icon definitely needs to change, as I agree it is pretty confusing right now.
