### ISSUE TITLE
Different title preview

### ISSUE THREAD

**Issue by VankoIvanov** [SoftUni-Internal/hackathon-issues#180]
**Describe the bug**
Different title preview 

**Steps To Reproduce**
By hovering over the title. It's somewhere small and above the title. Elsewhere it is distinctly shaped and large

**Screenshots**
![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/74661739/f7462cbc-8f19-4998-9065-8e7f93379335)
![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/74661739/a8cf158a-7ffb-4a75-b134-1fe051d15527)

**Additional context**

**Comment by Innos** [comment]
The above results are Contests, while the below are Problems, it's not surprising that they have a different way to visualize, though maybe there is an UI question, if problems and contests should look more distinct in the results.

**Comment by VankoIvanov** [comment]
I understand what the different categories are -  Contests and Problems. But I think the rendering of the entire header after hovering should be the same. And not once in form, but other times as a small text above the title. 
![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/74661739/83e7f7d2-45ab-4e40-8756-77c7290d5ea3)
![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/74661739/6d5b7fd2-0a61-46d0-9f35-9eec1c3e8ef7)
Obtained by pointing from the mouse cursor
