### ISSUE TITLE
Home button rename

### ISSUE THREAD

**Issue by PetkoAndreev** [SoftUni-Internal/hackathon-issues#181]
The home button in the navigation - proposition - either rename it to SoftUni Judge or change the link to which leads to be SoftUni website insteead of the judge itself.

![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/77919922/e6f886f9-a9c8-44bd-9902-51d0712fe97b)

**Comment by Innos** [comment]
I consider this the same as https://github.com/SoftUni-Internal/hackathon-issues/issues/179, so I'm marking this as a duplicate
