### ISSUE TITLE
Refreshing after change Contest category

### ISSUE THREAD

**Issue by PetkoAndreev** [SoftUni-Internal/hackathon-issues#186]
It's recommendation - after each click/change of contest category the page is refreshed and blue loading circle is showed. It can be changed like navigating between the tasks in a particular contest.

**Comment by Innos** [comment]
I imagine it would be a poor technical choice to do this. Problems in the contest can be preloaded I would guess, as there is a reasonable expectation that they would be viewed, on the other hand preloading paginated categories, that might never be visited sounds counterproductive.

Closing this issue as working as intended
