### ISSUE TITLE
Strategy - Weird Behaviour

### ISSUE THREAD

**Issue by KaiserDMC** [SoftUni-Internal/hackathon-issues#187]
**Describe the bug**
Upon selection a strategy it is never cleared unless "Clear filters" is clicked. 
However, even that does not always work properly (see issues #165 . 

The issue I experienced is that if you select a certain strategy for a certain Topic of Contests, if you then change the topic to one that does not have the certain strategy it will show as blank. However, if you then go back to another topic that has that strategy the filter will apply and the Dropdown will be populated once again.

**Steps To Reproduce**
Select "C# Project Tests" as Strategy then click on "C# Developement. (screenshot 1)
Move to "Mini Courses" or any other topic that does not have C#. (screenshot 2)
Go to "Others" where the Strategy is once again present. (screenshot 3)

**Screenshots**
1. 
![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/63681999/d10dbf24-6eb1-4f0c-838c-8533995d6b11)

2.
![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/63681999/950cd511-4fb4-4122-b02e-1a14de9d50e9)

3.
![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/63681999/8c8dda08-57ed-4f7b-8346-34304db83e95)

**Additional context**
The filters are applied, but they are not shown/visible. Thus the user will rightfully think they have been cleared from the filters.

**Comment by Innos** [comment]
After discussion, the strategy filter applying, even when selecting a category that does not contain that strategy is the more intuitive way the category filter should work (to support looking through different categories for contests allowing a specific strategy, which is the entire idea of the strategy filter). But it does need some small fixes and UI improvements, for the select to show the currently selected/filtered strategy even if it's not part of the options and also to maybe show an applied filter info in a similar way as it shows the currently selected category.
