### ISSUE TITLE
Contact Us - Form

### ISSUE THREAD

**Issue by KaiserDMC** [SoftUni-Internal/hackathon-issues#188]
**Describe the bug**
Broken links in the "Contact Us" form. The redirects for the official Instagram and Twitter/X profile are broken.
While the ones provided on the current website are valid and working.

**Steps To Reproduce**
Go to https://learn.softuni.org/contact
Try to use the Redirects for Instagram or Twitter/X.

**Screenshots**
![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/63681999/a24b8ffe-f9c5-44c5-88ba-f2aca9796fef)

![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/63681999/2b9557ef-882c-4495-83f4-612a0936ba83)

**Additional context**
It seems like that the Instagram one is redirecting to "softuni_org" while the current address is "softuni.bg"

**Comment by Innos** [comment]
This issue is not relevant to the judge as it is for a different site, so I'm marking it as invalid.
