### ISSUE TITLE
Refresh button

### ISSUE THREAD

**Issue by VankoIvanov** [SoftUni-Internal/hackathon-issues#189]
**Describe the bug**
If no decision is submit. The refresh button must be hidden, otherwise nothing refreshes

**Steps To Reproduce**

**Screenshots**
![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/74661739/1dbe5f3d-1516-4359-97c2-b49bdaaecf5a)
**Additional context**

**Comment by Innos** [comment]
Closing this recommendation, as the way submissions will be loaded is going to change and is expected to not need a refresh button.
