### ISSUE TITLE
They throw some requests and throw errors

### ISSUE THREAD

**Issue by VankoIvanov** [SoftUni-Internal/hackathon-issues#191]
**Describe the bug**

**Steps To Reproduce**
When you are on the contest page and open devTools

**Screenshots**
![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/74661739/2267fb2d-d331-4dcc-86fc-03c92b343d85)

**Additional context**

**Comment by Innos** [comment]
I'm leaving it as investigate and Recommendation as it isn't really connected to an identifiable underlying issue, though I will pass it on to be investigated.
