### ISSUE TITLE
Submissions request

### ISSUE THREAD

**Issue by VankoIvanov** [SoftUni-Internal/hackathon-issues#192]
**Describe the bug**

**Steps To Reproduce**
When you are on the Submissions page and open devTools

**Screenshots**
![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/74661739/6a326965-3719-4432-baba-21ecde92b989)

**Additional context**

**Comment by veronika793** [comment]
related https://github.com/SoftUni-Internal/hackathon-issues/issues/191

**Comment by Innos** [comment]
I'm leaving it as investigate and Recommendation as it isn't really connected to an identifiable underlying issue, though I will pass it on to be investigated.

**Comment by Innos** [comment]
Removing Recommendation label and linking it in an issue, that this is probably related to.
