### ISSUE TITLE
Responsive design Navbar

### ISSUE THREAD

**Issue by VankoIvanov** [SoftUni-Internal/hackathon-issues#193]
**Describe the bug**

When the screen is reduced, the navigation bar breaks and the buttons come out of it
**Steps To Reproduce**

**Screenshots**
![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/74661739/afeb1765-75a8-401d-8786-b698b08623ec)

**Additional context**

**Comment by Innos** [comment]
Marking this as Already in repo, since after discussing it, the issues with responsive are already known.
