### ISSUE TITLE
 Category recommendation

### ISSUE THREAD

**Issue by VankoIvanov** [SoftUni-Internal/hackathon-issues#194]
**Describe the bug**

When shrinking the screen, it would be nice to have the categories shrink as well, not just the main content.

**Steps To Reproduce**

**Screenshots**
![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/74661739/58a3d98f-cb55-4d3d-b9ff-fe11d518d663)

**Additional context**

**Comment by Innos** [comment]
Sub issue to https://github.com/SoftUni-Internal/hackathon-issues/issues/193 also about responsive
