### ISSUE TITLE
Mobile version

### ISSUE THREAD

**Issue by VankoIvanov** [SoftUni-Internal/hackathon-issues#195]
**Describe the bug**
When opening a race, the first button is cut off

**Steps To Reproduce**

**Screenshots**
![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/74661739/41e57847-80b2-4bcb-8d25-89344a3380fa)

**Additional context**

**Comment by Innos** [comment]
Sub issue to https://github.com/SoftUni-Internal/hackathon-issues/issues/193 also about responsive
