### ISSUE TITLE
Button alignment on mobile version

### ISSUE THREAD

**Issue by VankoIvanov** [SoftUni-Internal/hackathon-issues#196]
**Describe the bug**
On the submit page, under the black console the two buttons are not aligned

**Steps To Reproduce**

**Screenshots**
![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/74661739/90357f2e-0a86-4668-9af6-54619e2f5217)

**Additional context**

**Comment by Innos** [comment]
Sub issue to https://github.com/SoftUni-Internal/hackathon-issues/issues/193 as it is also connected to responsive
