### ISSUE TITLE
 Not correct information

### ISSUE THREAD

**Issue by VankoIvanov** [SoftUni-Internal/hackathon-issues#199]
**Describe the bug**

**Steps To Reproduce**
The submissions page keeps saying "Latest 15 submissions out of 3.0 K total" 
This is not true

**Screenshots**
![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/74661739/bf260beb-907b-448d-9b7c-cdaf87ee42fa)

**Additional context**

**Comment by Innos** [comment]
The submission count is actually correct, it is cached and updated at certain intervals, but to prevent confusion, it is important to note that this number does not reflect the amount of submissions in the normal judge, but actually the new judge.
