### ISSUE TITLE
Click Pending - Error 401

### ISSUE THREAD

**Issue by VankoIvanov** [SoftUni-Internal/hackathon-issues#201]
**Describe the bug**

**Steps To Reproduce**

Clicking on Pending results in a blank page and a 401 error 

**Screenshots**
![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/74661739/e259deda-e18c-4bf5-8430-fff560a0dc51)

**Additional context**

**Comment by veronika793** [comment]
related https://github.com/SoftUni-Internal/hackathon-issues/issues/200

**Comment by Innos** [comment]
Sub issue to: https://github.com/SoftUni-Internal/hackathon-issues/issues/200
