### ISSUE TITLE
Button My Submissions -  did not work

### ISSUE THREAD

**Issue by VankoIvanov** [SoftUni-Internal/hackathon-issues#202]
**Describe the bug**

**Steps To Reproduce**

If you click first on In Queue or Pending and then on My Submissions, there are no results

Then when you refresh the page, the results come out

**Screenshots**
![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/74661739/94567e70-f617-4ca8-8fc2-cf9601a0d021)
![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/74661739/30be7b8f-0d8e-4c88-9aee-18ddbb4497af)

**Additional context**

**Comment by Innos** [comment]
Seems to also be connected and possibly as sub issue to https://github.com/SoftUni-Internal/hackathon-issues/issues/200
