### ISSUE TITLE
Lab without assignments

### ISSUE THREAD

**Issue by VankoIvanov** [SoftUni-Internal/hackathon-issues#205]
**Describe the bug**

If there are no tasks to solve in the lab. Score should be 0/0, not 0/600
**Steps To Reproduce**

**Screenshots**
![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/74661739/63e363e4-0af3-45fa-aec0-56e3523a93b2)

**Additional context**

**Comment by Innos** [comment]
Link to contest https://alpha.judge.softuni.org/contests/2447/compete#1

**Comment by VankoIvanov** [comment]
Last night as system tests I didn't get any tasks. It can be seen in the screenshot. Or there is a problem loading the tasks and viewing them. How many times have I tried to load the page
