### ISSUE TITLE
Lab exercises without assignments - see results

### ISSUE THREAD

**Issue by VankoIvanov** [SoftUni-Internal/hackathon-issues#206]
**Describe the bug**
If there are no tasks to solve in the lab. There should be no results button. And the results page should not show the assignments

**Steps To Reproduce**

**Screenshots**
![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/74661739/951638fe-f305-4b69-87d2-938bfec9c947)

![image](https://github.com/SoftUni-Internal/hackathon-issues/assets/74661739/8bbef359-6120-41d0-a395-d5869091a0d8)

**Additional context**

**Comment by veronika793** [comment]
related https://github.com/SoftUni-Internal/hackathon-issues/issues/205

**Comment by Innos** [comment]
There are in fact 6 problems in the contest, https://github.com/SoftUni-Internal/hackathon-issues/issues/205 is the real bug, as it didn't show you the problems in the contest, but the results are working as intended, as there are indeed 6 problems in the contest.
