### ISSUE TITLE
Back

### ISSUE THREAD

**Issue by VankoIvanov** [SoftUni-Internal/hackathon-issues#23]
**Describe the bug**

Once you open to view the details of the uploaded solution, you cannot go back
**Steps To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/74661739/207859092-60ed308e-66f5-4eb0-a674-330ff7dc4e52.png)

**Additional context**

**Comment by Innos** [comment]
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/3
