### ISSUE TITLE
Openings C# and JS submissions of other poeople doesnt show my submissions on the right

### ISSUE THREAD

**Issue by Boyan-Apostolov** [SoftUni-Internal/hackathon-issues#24]
**Describe the bug**
When i choose someone's submission, I see my submissions on the right side of the screen, but if I choose a c# or JS submission, then my submissions stay empty.(may still occur with other types of submissions)

**Steps To Reproduce**
[screen-capture (1).webm](https://user-images.githubusercontent.com/58187770/207859095-a497b7d7-b17f-43bd-901e-567ce33e1027.webm)

**Screenshots**
(see attached video)

**Additional context**

**Comment by Innos** [comment]
Have to check if he actually had any submissions for this problem, cause if not, it makes sense nothing is shown

**Comment by MadjarovaML** [comment]
After we lock the submissions no regular user will be able to open other submissions than his own
