### ISSUE TITLE
Code textarea is constantly dark

### ISSUE THREAD

**Issue by dtdimitrovv** [SoftUni-Internal/hackathon-issues#25]
**Describe the bug**
Code textarea is constantly dark regardless of the theme in the browser (my is DarkReader). This is visibly not appealing

**Steps To Reproduce**

Open a task and try to submit a solution for it

**Screenshots**
![image](https://user-images.githubusercontent.com/86721304/207859230-8a0f0f47-73b1-4307-9567-76e5257e7e99.png)
![image](https://user-images.githubusercontent.com/86721304/207859301-5858e521-d91f-41e5-8f85-8c6170fca273.png)

**Additional context**

**Comment by MadjarovaML** [comment]
@Innos this is expected behavior, this is the tam of the code editor.
