### ISSUE TITLE
Can not see results

### ISSUE THREAD

**Issue by AntoanPetrov123** [SoftUni-Internal/hackathon-issues#32]
**Describe the bug**

Can't see results
**Steps To Reproduce**

**Screenshots**

![image](https://user-images.githubusercontent.com/72857425/207860259-2a36cb00-141c-4233-951e-e03a99f8acea.png)

**Additional context**

**Comment by Innos** [comment]
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/5
