### ISSUE TITLE
Profile update

### ISSUE THREAD

**Issue by PetkoAndreev** [SoftUni-Internal/hackathon-issues#38]
After click on update button in profile page it directly redirects to home. No edit button and all in the profile is disabled for editing.

**Comment by Innos** [comment]
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/7

**Comment by PetkoAndreev** [comment]
Agree, but as a suggestion it'll be good to add edit functionality or a possibility to remove contest or something similar as a logic, because in the current situation the Update button is pretty much useless.
