### ISSUE TITLE
Blurry fields on login page

### ISSUE THREAD

**Issue by dtdimitrovv** [SoftUni-Internal/hackathon-issues#39]
**Describe the bug**
When we access the login form with a browser that has a DarkReader extension the username and password fields are somehow blurry

**Steps To Reproduce**
Try to log in

**Screenshots**
![image](https://user-images.githubusercontent.com/86721304/207861024-6a040f84-a8ee-4d11-bfe5-d760b612f5ca.png)
![image](https://user-images.githubusercontent.com/86721304/207861500-f68efd76-77c7-44dd-b880-64b284dbbcf7.png)

**Additional context**
The second image shows DarkReader configuration

**Comment by Innos** [comment]
Seems to be an issue with how external extensions modify the page, not a problem with the system per se.
