### ISSUE TITLE
Scroll does not work when the mouse cursor is in the textarea where we place the code

### ISSUE THREAD

**Issue by dtdimitrovv** [SoftUni-Internal/hackathon-issues#4]
**Describe the bug**
Mouse cursor not active in code area 

**Steps To Reproduce**
1 - Open the page for a given task
2 - Move the cursor in the area provided for the code
3 - Try to scroll with the mouse

**Screenshots**

**Additional context**

**Comment by Innos** [comment]
When mouse cursor is over the code area, it scrolls the code area, but maybe there were not enough lines to see the scrolling?

**Comment by dtdimitrovv** [comment]
I agree this could be the case.

**Comment by MadjarovaML** [comment]
@Innos consider if you want to open the issue in our repo with more details as I don't see a problem.
