### ISSUE TITLE
Duplicate text contest password form 

### ISSUE THREAD

**Issue by dtdimitrovv** [SoftUni-Internal/hackathon-issues#44]
**Describe the bug**
When the open the contest password form we see 2 times "Password"

**Steps To Reproduce**
Open the contest password page

**Screenshots**
![image](https://user-images.githubusercontent.com/86721304/207861834-7ac21285-e61b-4710-be32-dbeb9a2a8afc.png)

**Additional context**

**Comment by Innos** [comment]
Seems to be a problem with external extensions, not a problem in the system per se.
