### ISSUE TITLE
Incorrect update button redirection

### ISSUE THREAD

**Issue by dtdimitrovv** [SoftUni-Internal/hackathon-issues#47]
**Describe the bug**
The redirect button redirects to the home page (see the left bottom part of the screenshot)

**Steps To Reproduce**
1 - Open "My Profile"
2 - Click on update

**Screenshots**
![image](https://user-images.githubusercontent.com/86721304/207862201-d21f5a3b-6228-464b-b762-e187c370fb19.png)

**Additional context**

**Comment by Innos** [comment]
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/7
