### ISSUE TITLE
Confusing number in the submissions section of "My Profile" page

### ISSUE THREAD

**Issue by dtdimitrovv** [SoftUni-Internal/hackathon-issues#51]
**Describe the bug**
Open "My Profile" page. Observe the submissions section. The number is 5 that is equivalent to the number the tasks in the Hackaton. In reality they are no solved to be present.

**Steps To Reproduce**
1 - Open "My Profile" page
2 - Observe the value in the "Submissions" section

**Screenshots**
![image](https://user-images.githubusercontent.com/86721304/207862897-b7fbbafa-33fd-432b-a55f-aad7dd4a96c9.png)

**Additional context**

**Comment by Innos** [comment]
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/2
