### ISSUE TITLE
Cannot navigate back after details page

### ISSUE THREAD

**Issue by AntoanPetrov123** [SoftUni-Internal/hackathon-issues#52]
**Describe the bug**
Cannot navigate back after details page

**Steps To Reproduce**

Have to refresh details, then can go back to contest

**Screenshots**
![image](https://user-images.githubusercontent.com/72857425/207863196-7c531a10-7e4c-469f-9f67-8b79fd41f855.png)

**Additional context**

**Comment by Innos** [comment]
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/3
