### ISSUE TITLE
Seeing other people's solutions

### ISSUE THREAD

**Issue by VankoIvanov** [SoftUni-Internal/hackathon-issues#56]
**Describe the bug**
You can move around and access other people's solutions and pages

**Steps To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/74661739/207863600-34456844-cff8-4bba-80d0-6ceea418aa9e.png)

**Additional context**

**Comment by Innos** [comment]
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/16
