### ISSUE TITLE
There is no direct link to contest

### ISSUE THREAD

**Issue by DesislavaTopuzakova** [SoftUni-Internal/hackathon-issues#59]
**Describe the bug**
When entering details of the submission there is no direct link to the contest from the details

**Steps To Reproduce**
1. Enter in details of the submission
2. There is no way back to the contest

**Screenshots**
![image](https://user-images.githubusercontent.com/34713586/207864232-914fdc1f-9a8a-4693-8fdd-00bb724ae6b2.png)

**Additional context**

**Comment by MadjarovaML** [comment]
this will be solved with our "back to contest" button which is already logged n our repo
