### ISSUE TITLE
Resources

### ISSUE THREAD

**Issue by VankoIvanov** [SoftUni-Internal/hackathon-issues#6]
**Describe the bug**

It is available in Bulgarian and English

**Steps To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/74661739/207854563-5e3d416e-37a9-48a9-99a5-245132e4dad7.png)

**Additional context**

**Comment by MadjarovaML** [comment]
It is just the name of the file. It will appear in the language you wrote it.

**Comment by Innos** [comment]
Yes, it works as intended, not a problem with the system
