### ISSUE TITLE
Cannot show columns in My Page after hiding all of them.

### ISSUE THREAD

**Issue by kalin729** [SoftUni-Internal/hackathon-issues#61]
**Describe the bug**
After hiding all columns from the My Profile > Contest Participations, you cannot un-hide them, unless refreshing page.
After hiding them, the table still remains with 5 empty rows. It would be better if there's at least one mandatory row to be shown and an option to un-hide.

**Steps To Reproduce**
1. Open "My Profile"
2. Open "Contest Participations"
3. Click on the 3 dots on any column
4. Click "Show Columns"
5. Click "HIDE ALL"
6. Close "Show Columns" window

**Screenshots**
![image](https://user-images.githubusercontent.com/24556064/207864503-a1d18769-3313-4138-b6ad-8188d81097fc.png)

![image](https://user-images.githubusercontent.com/24556064/207864522-cb8c7423-d938-4215-95e6-9792262b07b5.png)

![image](https://user-images.githubusercontent.com/24556064/207864531-4c67b43c-1f7b-4ded-8f05-0bd8928d5b3c.png)

![image](https://user-images.githubusercontent.com/24556064/207864538-fc0cbac8-9240-4094-91ea-56682fbfc869.png)

**Comment by MadjarovaML** [comment]
@Innos  I tried several times and the functionality seems to work pretty fine. 
I tried one by one and all in once
