### ISSUE TITLE
Different timers in home and contest pages

### ISSUE THREAD

**Issue by PetkoAndreev** [SoftUni-Internal/hackathon-issues#68]
In the contest page I see only time for the Compete - https://judgesoftuniorg.ml/contests/3308/compete#1:
![image](https://user-images.githubusercontent.com/77919922/207865897-5e1931a1-6cce-4d3d-a554-ba8b3e5e8733.png)
In the home page the timer is different and it shows the whole time, including Compete + Practice:
![image](https://user-images.githubusercontent.com/77919922/207866039-61f9a38a-ebc8-4300-82a7-e2d166962c82.png)

**Comment by Innos** [comment]
One is the contest duration i.e. the time during which you can start competing and the other is the personal duration you have to complete the competition.

**Comment by Innos** [comment]
Same answer as in this issue https://github.com/SoftUni-Internal/hackathon-issues/issues/122

**Comment by PetkoAndreev** [comment]
That's ok, but let's say you start the contest, click on the home and see that you have 9 more hours. You may think this is the real time and if something pops up and you go away from PC and do this additional think, come back in 4 hours and realize that this timer confuse you. As a proposition will be good when the contest is started by user the timer in both places - the contest page, list of contest and on the home page.
