### ISSUE TITLE
Current points

### ISSUE THREAD

**Issue by VankoIvanov** [SoftUni-Internal/hackathon-issues#70]
**Describe the bug**
After the system has recorded a correct task in the total points, the result does not change, you must click refresh to see all the points from the last commit

**Steps To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/74661739/207866268-1fd55fbe-ee8a-4e03-849b-c08b8fbd3d23.png)

**Additional context**

**Comment by Innos** [comment]
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/20
