### ISSUE TITLE
Cannot load details when I have points

### ISSUE THREAD

**Issue by AntoanPetrov123** [SoftUni-Internal/hackathon-issues#71]
**Describe the bug**
Cannot see the details page when I get points 

**Steps To Reproduce**
After reload they show up

**Screenshots**

![image](https://user-images.githubusercontent.com/72857425/207866163-f0c58b73-0ef3-4954-abf7-4d82189e8d23.png)

**Additional context**

**Comment by Innos** [comment]
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/18
