### ISSUE TITLE
Submissions page time formatting 

### ISSUE THREAD

**Issue by kalin729** [SoftUni-Internal/hackathon-issues#72]
**Describe the bug**
In the Submissions page, the time of the submission and author must have a blank spaces.
In the provided example the text is "4 minutes agobykalin729ht", where my username is "kalin729ht".
The right format should be "4 minutes ago by kalin729ht".

**Steps To Reproduce**
Open "Submissions" page.

**Screenshots**
![image](https://user-images.githubusercontent.com/24556064/207867068-f40981a8-6d46-4683-a52f-bfd71dd4ae8c.png)

**Comment by Innos** [comment]
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/22
