### ISSUE TITLE
ui got broken

### ISSUE THREAD

**Issue by kkaraivanov** [SoftUni-Internal/hackathon-issues#73]
**Describe the bug**
when minimizing the window, the interface breaks

**Steps To Reproduce**

**Screenshots**
![Capture](https://user-images.githubusercontent.com/55097619/207867641-abe957d6-7418-4166-960e-98312de624e6.PNG)

**Additional context**

**Comment by Innos** [comment]
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/26
