### ISSUE TITLE
Profile - My Submissions

### ISSUE THREAD

**Issue by PetkoAndreev** [SoftUni-Internal/hackathon-issues#74]
When I'm in the profile page I'm seeing the contests in which I participate, but when I hover the contest name the cursor changes, but it's not a link to navigate to the particular contest.
![image](https://user-images.githubusercontent.com/77919922/207868151-b2591422-913f-4945-91c3-b46d4257abf3.png)

**Comment by Innos** [comment]
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/64
