### ISSUE TITLE
Contests menu - blinks while loading

### ISSUE THREAD

**Issue by PetkoAndreev** [SoftUni-Internal/hackathon-issues#75]
When click on the Contests in the menu bar it blinks few times before fully load:
![image](https://user-images.githubusercontent.com/77919922/207868497-fbc2a8ab-075a-411f-b1d0-0deafdaf1e4d.png)

**Comment by Innos** [comment]
This by itself does not sound like a problem, screen is grayed out and there is a loader while data is loading, which seems ok for me.  Please provide extra information, so we'll know if there as actual issue or not.

**Comment by Innos** [comment]
@PetkoAndreev Can you provide some details, am I missing something, otherwise it looks to be working as expected to me and I'll close the issue.

**Comment by Innos** [comment]
Nevermind, I checked it again a few times. I'm marking this as enhancement, partial versions of the page flash for miliseconds before showing the entire version, but this can probably be solved with delaying rendering until all content is loaded
