### ISSUE TITLE
Clicking on Register from header, leaves site on a refresing loop.

### ISSUE THREAD

**Issue by kalin729** [SoftUni-Internal/hackathon-issues#79]
**Describe the bug**
When you cclick the "Register" button from the Judge header it bugs the website on a loop that keeps refreshing the page.

**Steps To Reproduce**
1. Open Judge.
2. Click "Register" from the header.

**Screenshots**
![image](https://user-images.githubusercontent.com/24556064/207870332-7ca70bfd-85db-4af5-b4e7-ee3afc630d65.png)

**Comment by Innos** [comment]
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/31
