### ISSUE TITLE
Merge text

### ISSUE THREAD

**Issue by VankoIvanov** [SoftUni-Internal/hackathon-issues#80]
**Describe the bug**
In the page submissions, the time when the solution was uploaded and the username are merged

**Steps To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/74661739/207870202-964c2314-82f2-41e4-ab47-a2a963a74a0e.png)

**Additional context**

**Comment by Innos** [comment]
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/22
