### ISSUE TITLE
Contests mix of languages

### ISSUE THREAD

**Issue by PetkoAndreev** [SoftUni-Internal/hackathon-issues#85]
When open  Contests page and play a little with sorting/searching I saw that some contests are in English and some in Bulgarian. 
![image](https://user-images.githubusercontent.com/77919922/207872167-e89946b0-7590-4677-a268-eab026bb1626.png)

**Comment by Innos** [comment]
Part of the administration, some contests have Cyrillic names and some have Latin, works as intended and it's not a problem with the system

**Comment by PetkoAndreev** [comment]
As for the resources languages - as a proposition in order as a best practice - it'll be good all the text to be in one language, not mixed.
