### ISSUE TITLE
Resources

### ISSUE THREAD

**Issue by VankoIvanov** [SoftUni-Internal/hackathon-issues#9]
**Describe the bug**

there is a checkbox when downloading resources.

**Steps To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/74661739/207854938-fb2c1d19-3c1c-4f8e-8653-e25e0c5246cd.png)

**Additional context**

**Comment by Innos** [comment]
Seems like the font awesome icon does not display as "fas" class is missing

**Comment by MadjarovaML** [comment]
@Innos as it is an icon, please discuss in Training team if we must change it and log us an issue
