### ISSUE TITLE
Contests page sorting

### ISSUE THREAD

**Issue by PetkoAndreev** [SoftUni-Internal/hackathon-issues#96]
When put some sorting like by End Date it's ok. When click for the second time on End Date it automatically picks the Start Date as a filter. What will happen if a user wants no sorting?
![image](https://user-images.githubusercontent.com/77919922/207875383-3f51cc21-c9e8-4218-86ae-0a520f325965.png)
![image](https://user-images.githubusercontent.com/77919922/207875493-76e7667a-7a8b-4e2a-8387-e0eeb7058a66.png)

**Comment by MadjarovaML** [comment]
we must have some default sorting and it is by Start date 
@Innos if you decide that another default sorting must be applied, please log an issue in our repo or contact me.
