### ISSUE TITLE
Symmetry

### ISSUE THREAD

**Issue by VankoIvanov** [SoftUni-Internal/hackathon-issues#97]
**Describe the bug**

In section contest there is no symmetry to the current races in the section
**Steps To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/74661739/207875266-99ee86d7-c446-4e94-a890-d5b0efd5afb7.png)

**Additional context**

**Comment by Innos** [comment]
Duplicate of https://github.com/SoftUni-Internal/hackathon-issues/issues/90
